### ISSUE TITLE
ユーザー名でログインができない

### ISSUE THREAD

**Issue by nakasyou** [ActiveTK/MetaNote#3]
### Summary
ユーザー名でログインができません。メールアドレスだとできました。
### Steps to reproduce:

1. https://metanote.org/login で、自分の**ユーザー名**とパスワードを入力する
2. ログインされない
3. 自分の**eメールアドレス**とパスワードを入力する
4. ログインに成功する
### 内容
ユーザー名でログインすることができません。メールアドレスだとできました。
ログイン画面の、ユーザー名入力欄の`placeholder`属性には、ユーザー名でログインが可能の書いてあります。

### 実行環境
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
```

**Comment by ActiveTK** [comment]
ご指摘ありがとうございます。

placeholderの`ユーザー名`とは、それぞれのユーザーに割り当てられる`ユーザーID`(半角英数)を意図していました。
ユーザーが任意に設定できるユーザー名は重複を許しているため、ログイン先のアカウントを一意に定めることができず、そのためユーザー名によるログイン処理の実装はできません。

つきまして、`placeholder`の曖昧な表現を修正させて頂きます。

なお、プログラム内では以下のような処理を行っています。
```
    try {
      $stmt = $dbh->prepare('select * from MetaNoteUsers where Mailadd = ? or UserIntID = ? or DisplayID = ? limit 1;');
      $stmt->execute( [$Try_User, $Try_User, $Try_User] );
      $row = $stmt->fetch( PDO::FETCH_ASSOC );
    } catch ( \Throwable $e ) {
      MetaNote_Fatal_Die( $e->getMessage() );
    }
```

**Comment by nakasyou** [comment]
ご回答ありがとうございました。
